In [2]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [5]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#tạo mảng toàn là số 0
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [7]:
#tạo mảng toàn số 1
np.ones((3,4),dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [10]:
np.arange(0,25,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [11]:
np.full((3,4),57)

array([[57, 57, 57, 57],
       [57, 57, 57, 57],
       [57, 57, 57, 57]])

In [14]:
# tạo mảng có n phần tử với giá trị từ a đến b np.linspace(a,b,n)
np.linspace(2,9,5)

array([2.  , 3.75, 5.5 , 7.25, 9.  ])

In [21]:
#tạo mảng với random 
np.random.random((3,4))

array([[0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ]])

In [25]:
# dùng để tạo ngẫu nhiên nhưng các lần chạy giá trị không đổi
np.random.seed(0)
np.random.rand(3,4)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [24]:
np.random.normal(1,3,(3,4))

array([[ 1.9392031 , -1.56228722, -6.65896945,  2.96085579],
       [ 3.5933086 , -1.22649506,  7.80926387, -3.36309702],
       [ 1.13727555,  0.43844845,  5.59833764,  5.40807631]])

In [26]:
np.random.randint(0,10,(3,4))

array([[8, 1, 5, 9],
       [8, 9, 4, 3],
       [0, 3, 5, 0]])

In [29]:
x=np.random.randint(20, size=7)
x

array([11, 18,  2,  0,  0,  4,  5])

In [33]:
x[-1],x[0],x[2] 

(5, 11, 2)

In [35]:
n=np.random.randint(20, size=(3,4))
n

array([[ 6, 11, 14, 18],
       [ 0, 14,  3, 12],
       [10, 11,  4,  6]])

In [36]:
n[-1,-1]

6

In [37]:
n[-1,-1]=8

In [41]:
n[-1,-1]

8

In [40]:
n

array([[ 6, 11, 14, 18],
       [ 0, 14,  3, 12],
       [10, 11,  4,  8]])

In [42]:
x

array([11, 18,  2,  0,  0,  4,  5])

In [43]:
x[0:4] #lấy giá trị từ 0 đến giá trị thứ 4

array([11, 18,  2,  0])

In [45]:
x[::2] # lấy giá trị đầu đến cuối step là 2

array([11,  2,  0,  5])

In [46]:
n

array([[ 6, 11, 14, 18],
       [ 0, 14,  3, 12],
       [10, 11,  4,  8]])

In [48]:
n[:3,:2]

array([[ 6, 11],
       [ 0, 14],
       [10, 11]])

In [49]:
np.sum(x)

40

In [50]:
np.mean(x)

5.714285714285714

In [51]:
np.max(x)

18

In [52]:
np.min(x)

0

In [56]:
np.sort(x) # sort theo value

array([ 0,  0,  2,  4,  5, 11, 18])

In [57]:
np.argsort(x) # sort theo index

array([3, 4, 2, 5, 6, 0, 1])

In [54]:
np.sort(n)

array([[ 6, 11, 14, 18],
       [ 0,  3, 12, 14],
       [ 4,  8, 10, 11]])

In [58]:
np.sort(n,axis=0)

array([[ 0, 11,  3,  8],
       [ 6, 11,  4, 12],
       [10, 14, 14, 18]])

In [59]:
np.sort(n,axis=1)

array([[ 6, 11, 14, 18],
       [ 0,  3, 12, 14],
       [ 4,  8, 10, 11]])